### ISSUE TITLE
CSS organization structure for each ERB Page

### ISSUE THREAD

**Issue by jameschen208** [kylejbennett/SinatraDroneSite#4]

**Comment by kylejbennett** [comment]
Working on this now...

**Comment by bredia57821210** [comment]
Hi guys. Something is temporarily very wrong with this laptop when it comes
to Github (enough that even John hasn't been able to figure it out yet) but
in the meantime i wanted to share with you guys how to do this; if you
already know how then i apologize, but we never went over it in class so i
figured i'd at least save you the research time:

*in "public" folder --*   folder called "css", containing ____.css (main,
style, whatever)

*in layout.erb --*   <%= stylesheet_link_tag “/public/css/____.css" %>
(equivalent to the yield wrap; this css will show up on every page of our
site)

*in .rb file --*
get '/css/___.css' do
     erb :style
end

**Comment by jameschen208** [comment]
@kylejbennett completed structure for CSS
